### ISSUE TITLE
Don't force $GOPATH/src/github.com

### ISSUE THREAD

**Issue by codekoala** [tcnksm/gcli#48]
I wanted to generate a project that will not reside on github, and gcli created the project as if that were my plan. There should be an option to specify the host, or, at the very least, to create the project structure in a directory of the user's choosing.

**Comment by tcnksm** [comment]
Thanks for Issue.

Actually I'm thinking to enable to change it by option. I'll make this change for next version `v0.2.4`.

**Comment by tcnksm** [comment]
Hi, now you can change VCS host name via `-vcs` option flag https://github.com/tcnksm/gcli/pull/52

If you have other request, please open the Issue again :+1:

**Comment by codekoala** [comment]
Awesome, thanks!
