### ISSUE TITLE
username assumed for generation path

### ISSUE THREAD

**Issue by thoroc** [tcnksm/gcli#65]
The user name is assumed based on the gitconfig. Could there be somewhere in the documentation a mention of using the github.user from the .gitconfig? I had to go read the file ```tcnksm/gcli/command/new.go``` line 73-87 to understand why gcli would try to create a new folder under my full name.

Thanks

**Comment by tcnksm** [comment]
I will put comments. Thanks.

**Comment by tcnksm** [comment]
Done
